name: Run App for Lab

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NR_LICENSE_KEY: ${{ secrets.NR_LICENSE_KEY }}
      NR_APP_NAME: "demo-change-tracking"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Update packages and resolve dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install apt-transport-https ca-certificates curl software-properties-common

      - name: Add Docker GPG key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      - name: Add Docker repository
        run: |
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run Docker Compose with a 60m timer
        run: |
          docker-compose -f compose.yml up -d
          sleep 1h # Leave these containers running for 1 hour to give time to finish the lab
      
      - name: Stop containers
        run: |
          docker-compose -f compose.yml down || true
